### ISSUE TITLE
dnscrypt-proxy Incompatible signature algorithm

### ISSUE THREAD

**Issue by AndLLA** [Quad9DNS/dnscrypt-settings#8]
Using dns-crypt-proxy with the new configuration results in a "incompatible signature algorithm",
maybe related to the new minisign key ?

[2024-08-07 11:06:09] [NOTICE] dnscrypt-proxy 2.1.5
[2024-08-07 11:06:09] [NOTICE] Service is not usable yet
[2024-08-07 11:06:09] [NOTICE] Resolving server host [raw.githubusercontent.com] using bootstrap resolvers over udp
[2024-08-07 11:06:09] [NOTICE] Service is not usable yet
[2024-08-07 11:06:09] [NOTICE] Resolving server host [quad9.net] using bootstrap resolvers over udp
[2024-08-07 11:06:10] [CRITICAL] Unable to retrieve source [quad9-resolvers]: [Incompatible signature algorithm]
[2024-08-07 11:06:10] [FATAL] Incompatible signature algorithm

configuration:

  [sources.quad9-resolvers]
    urls = ['https://quad9.net/dnscrypt/quad9-resolvers.md', 'https://raw.githubusercontent.com/Quad9DNS/dnscrypt-settings/main/dnscrypt/quad9-resolvers.md']
    minisign_key = 'RWTp2E4t64BrL651lEiDLNon+DqzPG4jhZ97pfdNkcq1VDdocLKvl5FW'
    cache_file = '/var/cache/dnscrypt-proxy/quad9-resolvers.md'
    refresh_delay = 72
    prefix = 'quad9-'

**Comment by xbc5** [comment]
I can confirm this. Looks like [this commit](https://github.com/Quad9DNS/dnscrypt-settings/commit/bdcd404d46292736e66ed533e5ef4de0f7cbb0cb) causes the issue. I am not sure what went wrong, perhaps a bad key; or older packages in Linux repos are not up to scratch.

I am using dnscrypt-proxy-2.1.5-1.fc39.x86_64 on Fedora, but the latest stable version reported on the [homepage](https://www.dnscrypt.org/) is 1.9.5. 

Anyway, disabling the following soure fixes the issue:
```toml
[sources.quad9-resolvers]
  urls = ['https://www.quad9.net/quad9-resolvers.md']
  minisign_key = 'RWTp2E4t64BrL651lEiDLNon+DqzPG4jhZ97pfdNkcq1VDdocLKvl5FW'
  cache_file = '/var/cache/dnscrypt-proxy/quad9-resolvers.md'
  prefix = 'quad9-'
```

The [quad9 resolvers are available via the public resolver list](https://github.com/DNSCrypt/dnscrypt-resolvers/blob/f40e753f54028edf42dfbb402d722f59832222da/v3/public-resolvers.md?plain=1#L3374-L3569), which also have the `quad9-` prefix -- so if you have the public resolvers enabled, disabling this source will just use those, and everything should work.
